NWS-cs/Models/Advertisement.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NWS_cs
{
    public partial class Advertisement
    {
        public Advertisement()
        {
            link = "Content/Test/DefaultAd.jpg";
        }

        public int id { get; set; }

        [DisplayName("Advertisement Link")]
        [Required(ErrorMessage = "Advertisement link is required")]
        public string link { get; set; }
    }
}

NWS-cs/Models/Advertisements.cs
namespace NWS_cs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Advertisements
    {
        public int id { get; set; }

        public string link { get; set; }
    }
}

NWS-cs/Controllers/AdvertisementController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class AdvertisementController : Controller
    {
        private NwsContext db = new NwsContext();

        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        public ActionResult Content()
        {
            return View(db.Advertisements.ToList());
        }

        // GET: Advertisement/Create
        public ActionResult Create()
        {
            var model = new Advertisement();
            return View(model);
        }

        // POST: Advertisement/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "id,link")] Advertisement advertisement)
        {
            if (ModelState.IsValid)
            {
                db.Advertisements.Add(advertisement);
                db.SaveChanges();
                return RedirectToAction("Content");
            }

            return View(advertisement);
        }

        // GET: Advertisement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }

        // POST: Advertisement/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,link")] Advertisement advertisement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(advertisement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Content");
            }
            return View(advertisement);
        }

        // GET: Advertisement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }

        // POST: Advertisement/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Advertisement advertisement = db.Advertisements.Find(id);
            db.Advertisements.Remove(advertisement);
            db.SaveChanges();
            return RedirectToAction("Content");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NWS-cs/Controllers/EditController.cs
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class EditController : Controller
    {
        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

NWS-cs/Views/Advertisement/Content.cshtml
@model IEnumerable<NWS_cs.Advertisement>

@{
    ViewBag.Title = "Ad Content";
}

<div class="row bumpPastTopbar">
    @Html.Action("_EditButtonPartial", "Edit")

    <h4>Advertisements</h4>

    <p>
        <a href='@Url.Action("Create", "Advertisement")' class="button tiny">
            Create New
        </a>
    </p>

    @{
        foreach (var item in Model)
        {
            <div class="column small-12 panel">
                <div class="row">
                    <div class="column small-2 left">
                        <a href='@Url.Action("Edit", "Advertisement", new { id=item.id })'>
                            Edit
                        </a>|
                        <a href='@Url.Action("Delete", "Advertisement", new { id=item.id })'>
                            Delete
                        </a>
                    </div>

                    <div class="column small-10 left">
                        <div class="row">
                            <img class="smallPicture" src="~/@(Html.DisplayFor(modelItem => item.link))" alt="Ad image" />
                            @Html.DisplayFor(modelItem => item.link)
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Advertisement/Create.cshtml
@model NWS_cs.Advertisement

@{
    ViewBag.Title = "Ad Create";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Create an Advertisement</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.link)
            <div class="column small-12">
                @Html.EditorFor(model => model.link)
                @Html.ValidationMessageFor(model => model.link)
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Advertisement")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Advertisement/Delete.cshtml
@model NWS_cs.Advertisement

@{
    ViewBag.Title = "Ad Delete";
}

@using (Html.BeginForm())
{
    <div class="row bumpPastTopbar">
        <h4>Delete an Advertisement</h4>

        <h5>Are you sure you want to delete this?</h5>

        <div class="column small-12 panel">
            <div class="row">
                <div class="column small-12 small-offset-2 left">
                    <div>
                        <img class="smallPicture" src="~/@(Html.DisplayFor(model => model.link))" alt="Ad image" />
                        @Html.DisplayFor(model => model.link)
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Delete" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Advertisement")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Advertisement/Edit.cshtml
@model NWS_cs.Advertisement

@{
    ViewBag.Title = "Ad Edit";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Edit an Advertisement</h4>

        <div>
            @Html.LabelFor(model => model.link)
            <div class="column small-12">
                @Html.EditorFor(model => model.link)
                @Html.ValidationMessageFor(model => model.link)
            </div>
        </div>


        <div class="form-group">
            <input type="submit" value="Save" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Advertisement")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}