NWS-cs/Models/Video.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NWS_cs
{
    public partial class Video
    {
        public Video()
        {
            DateTime now = DateTime.Now;
            title = "New Video Title: " + now.ToString();

            site = "no_video";
            description = "Sorry, no video available.";
            link = "Content/Images/no_cat.jpg";
        }

        public int id { get; set; }

        [DisplayName("Video Site")]
        [Required(ErrorMessage = "Video site is required")]
        public string site { get; set; }

        [DisplayName("Video Mime Type")]
        public string type { get; set; }

        [DisplayName("Video Title")]
        [Required(ErrorMessage = "Video title is required")]
        public string title { get; set; }

        [DisplayName("Video Description")]
        public string description { get; set; }

        [DisplayName("Video Link")]
        [Required(ErrorMessage = "Video link is required")]
        public string link { get; set; }
    }
}

NWS-cs/Models/Videos.cs
namespace NWS_cs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Videos
    {
        public int id { get; set; }

        public string site { get; set; }

        public string type { get; set; }

        public string title { get; set; }

        public string description { get; set; }

        public string link { get; set; }
    }
}

NWS-cs/Controllers/EditController.cs
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class EditController : Controller
    {
        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

NWS-cs/Controllers/VideoController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class VideoController : Controller
    {
        private NwsContext db = new NwsContext();

        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        // GET: Video
        public ActionResult Content()
        {
            return View(db.Videos.ToList());
        }

        // GET: Video/Create
        public ActionResult Create()
        {
            var model = new Video();
            return View(model);
        }

        // POST: Video/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "id,site,type,title,description,link")] Video video)
        {
            if (ModelState.IsValid)
            {
                db.Videos.Add(video);
                db.SaveChanges();
                return RedirectToAction("Content");
            }

            return View(video);
        }

        // GET: Video/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = db.Videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // POST: Video/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,site,type,title,description,link")] Video video)
        {
            if (ModelState.IsValid)
            {
                db.Entry(video).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Content");
            }
            return View(video);
        }

        // GET: Video/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = db.Videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // POST: Video/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Video video = db.Videos.Find(id);
            db.Videos.Remove(video);
            db.SaveChanges();
            return RedirectToAction("Content");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NWS-cs/Views/Video/Content.cshtml
@model IEnumerable<NWS_cs.Video>

@{
    ViewBag.Title = "Video Content";
}

<div class="row bumpPastTopbar">
    @Html.Action("_EditButtonPartial", "Edit")

    <h4>Videos</h4>

    <p>
        <a href='@Url.Action("Create", "Video")' class="button tiny">
            Create New
        </a>
    </p>

    @{
        foreach (var item in Model)
        {
            <div class="column small-12 panel">
                <div class="row">
                    <div class="column small-2 left">
                        <a href='@Url.Action("Edit", "Video", new { id = item.id })'>
                            Edit
                        </a>|
                        <a href='@Url.Action("Delete", "Video", new { id = item.id })'>
                            Delete
                        </a>
                    </div>

                    <div class="column small-10 left">
                        <div>
                            @Html.DisplayFor(modelItem => item.site)
                        </div>
                        <div>
                            @Html.DisplayFor(modelItem => item.type)
                        </div>
                        <div>
                            @Html.DisplayFor(modelItem => item.title)
                        </div>
                        <div>
                            @Html.DisplayFor(modelItem => item.description)
                        </div>
                        <div>
                            @Html.DisplayFor(modelItem => item.link)
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Video/Create.cshtml
@model NWS_cs.Video

@{
    ViewBag.Title = "Video Create";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Create a Video</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.site)
            <div class="tab">
                <div>
                    No Video: @Html.RadioButtonFor(model => model.site, "no_video")
                </div>
                <div>
                    On-site: @Html.RadioButtonFor(model => model.site, "onsite")
                </div>
                <div>
                    Youtube: @Html.RadioButtonFor(model => model.site, "youtube")
                </div>
                @Html.ValidationMessageFor(model => model.site)
            </div>

            @Html.LabelFor(model => model.type)
            <div class="column small-12">
                @Html.EditorFor(model => model.type)
            </div>

            @Html.LabelFor(model => model.title)
            <div class="column small-12">
                @Html.EditorFor(model => model.title)
                @Html.ValidationMessageFor(model => model.title)
            </div>

            @Html.LabelFor(model => model.description)
            <div class="column small-12">
                @Html.EditorFor(model => model.description)
            </div>

            @Html.LabelFor(model => model.link)
            <div class="column small-12">
                @Html.EditorFor(model => model.link)
                @Html.ValidationMessageFor(model => model.link)
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Video")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Video/Delete.cshtml
@model NWS_cs.Video

@{
    ViewBag.Title = "Video Delete";
}

@using (Html.BeginForm())
{
    <div class="row bumpPastTopbar">
        <h4>Delete a Video</h4>

        <h5>Are you sure you want to delete this?</h5>

        <div class="column small-12 panel">
            <div class="row">
                <div class="column small-10 small-offset-2 left">
                    <div>
                        @Html.DisplayFor(model => model.site)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.type)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.title)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.description)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.link)
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Delete" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Video")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Video/Edit.cshtml
@model NWS_cs.Video

@{
    ViewBag.Title = "Video Edit";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Edit a Video</h4>

        <div>
            @Html.LabelFor(model => model.site)
            <div class="tab">
                <div>
                    No Video: @Html.RadioButtonFor(model => model.site, "no_video")
                </div>
                <div>
                    On-site: @Html.RadioButtonFor(model => model.site, "onsite")
                </div>
                <div>
                    Youtube: @Html.RadioButtonFor(model => model.site, "youtube")
                </div>
                @Html.ValidationMessageFor(model => model.site)
            </div>

            @Html.LabelFor(model => model.type)
            <div class="column small-12">
                @Html.EditorFor(model => model.type)
            </div>

            @Html.LabelFor(model => model.title)
            <div class="column small-12">
                @Html.EditorFor(model => model.title)
                @Html.ValidationMessageFor(model => model.title)
            </div>

            @Html.LabelFor(model => model.description)
            <div class="column small-12">
                @Html.EditorFor(model => model.description)
            </div>

            @Html.LabelFor(model => model.link)
            <div class="column small-12">
                @Html.EditorFor(model => model.link)
                @Html.ValidationMessageFor(model => model.link)
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Video")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}