NWS-cs/Models/Officer.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NWS_cs
{
    public partial class Officer
    {
        public Officer()
        {
            DateTime now = DateTime.Now;
            name = "New Officer Name: " + now.ToString();

            photo = "Content/Images/no_cat.jpg";
        }

        public int id { get; set; }

        [DisplayName("Officer Name")]
        [Required(ErrorMessage = "Officer name is required")]
        public string name { get; set; }

        [DisplayName("Officer Email")]
        [Required(ErrorMessage = "Officer email is required")]
        public string email { get; set; }

        [DisplayName("Officer Description")]
        public string description { get; set; }

        [DisplayName("Officer Photo")]
        public string photo { get; set; }
    }
}

NWS-cs/Models/Officers.cs
namespace NWS_cs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Officers
    {
        public int id { get; set; }

        public string name { get; set; }

        public string email { get; set; }

        public string description { get; set; }

        public string photo { get; set; }
    }
}

NWS-cs/Controllers/EditController.cs
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class EditController : Controller
    {
        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

NWS-cs/Controllers/OfficerController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class OfficerController : Controller
    {
        private NwsContext db = new NwsContext();

        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        // GET: Officer
        public ActionResult Index()
        {
            return View(db.Officers.ToList());
        }

        public ActionResult Content()
        {
            return View(db.Officers.ToList());
        }

        // GET: Officer/Create
        public ActionResult Create()
        {
            var model = new Officer();
            return View(model);
        }

        // POST: Officer/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "id,name,email,description,photo")] Officer officer)
        {
            if (ModelState.IsValid)
            {
                db.Officers.Add(officer);
                db.SaveChanges();
                return RedirectToAction("Content");
            }

            return View(officer);
        }

        // GET: Officer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Officer officer = db.Officers.Find(id);
            if (officer == null)
            {
                return HttpNotFound();
            }
            return View(officer);
        }

        // POST: Officer/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,name,email,description,photo")] Officer officer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(officer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Content");
            }
            return View(officer);
        }

        // GET: Officer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Officer officer = db.Officers.Find(id);
            if (officer == null)
            {
                return HttpNotFound();
            }
            return View(officer);
        }

        // POST: Officer/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Officer officer = db.Officers.Find(id);
            db.Officers.Remove(officer);
            db.SaveChanges();
            return RedirectToAction("Content");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NWS-cs/Views/Officer/Content.cshtml
@model IEnumerable<NWS_cs.Officer>

@{
    ViewBag.Title = "Officer Content";
}

<div class="row bumpPastTopbar">
    @Html.Action("_EditButtonPartial", "Edit")

    <h4>Neighborhood Association Officers</h4>

    <p>
        <a href='@Url.Action("Create", "Officer")' class="button tiny">
            Create New
        </a>
    </p>

    @{
        foreach (var item in Model)
        {
            <div class="column small-12 panel">
                <div class="row">
                    <div class="column small-2 left">
                        <a href='@Url.Action("Edit", "Officer", new { id = item.id })'>
                            Edit
                        </a>|
                        <a href='@Url.Action("Delete", "Officer", new { id = item.id })'>
                            Delete
                        </a>
                    </div>

                    <div class="column small-2 left">
                        <div class="row">
                            <img src="~/@(Html.DisplayFor(modelItem => item.photo))" alt="Officer image" />
                        </div>
                    </div>

                    <div class="column small-8 left">
                        <div>
                            @Html.DisplayFor(modelItem => item.name)
                        </div>
                        <div>
                            @Html.DisplayFor(modelItem => item.email)
                        </div>
                        <div>
                            @Html.DisplayFor(modelItem => item.description)
                        </div>
                        <div>
                            @Html.DisplayFor(modelItem => item.photo)
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Officer/Create.cshtml
@model NWS_cs.Officer

@{
    ViewBag.Title = "Officer Create";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Create an Officer</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.name)
            <div class="column small-12">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>

            @Html.LabelFor(model => model.email)
            <div class="column small-12">
                @Html.EditorFor(model => model.email)
                @Html.ValidationMessageFor(model => model.email)
            </div>

            @Html.LabelFor(model => model.description)
            <div class="column small-12">
                @Html.EditorFor(model => model.description)
            </div>

            @Html.LabelFor(model => model.photo)
            <div class="column small-12">
                @Html.EditorFor(model => model.photo)
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Officer")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Officer/Delete.cshtml
@model NWS_cs.Officer

@{
    ViewBag.Title = "Officer Delete";
}

@using (Html.BeginForm())
{
    <div class="row bumpPastTopbar">
        <h4>Delete an Officer</h4>

        <h5>Are you sure you want to delete this?</h5>

        <div class="column small-12 panel">
            <div class="row">
                <div class="column small-2 small-offset-2 left">
                    <div class="row">
                        <img src="~/@(Html.DisplayFor(model => model.photo))" alt="Officer image" />
                    </div>
                </div>

                <div class="column small-8 left">
                    <div>
                        @Html.DisplayFor(model => model.name)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.email)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.description)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.photo)
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Delete" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Officer")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Officer/Edit.cshtml
@model NWS_cs.Officer

@{
    ViewBag.Title = "Officer Edit";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Edit an Officer</h4>

        <div>
            @Html.LabelFor(model => model.name)
            <div class="column small-12">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>

            @Html.LabelFor(model => model.email)
            <div class="column small-12">
                @Html.EditorFor(model => model.email)
                @Html.ValidationMessageFor(model => model.email)
            </div>

            @Html.LabelFor(model => model.description)
            <div class="column small-12">
                @Html.EditorFor(model => model.description)
            </div>

            @Html.LabelFor(model => model.photo)
            <div class="column small-12">
                @Html.EditorFor(model => model.photo)
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Officer")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Officer/Index.cshtml
@model IEnumerable<NWS_cs.Officer>

@{
    ViewBag.Title = "Officers";
}

<div class="row bumpPastTopbar">
    <h4>Deer Park Neighborhood Association Officers</h4>

    <div class="row" data-equalizer>
        @{
            int index = 0;
            string[] colors = { "purpleA", "purpleB", "purpleC" };
            foreach (var item in Model)
            {
                <div class="column large-6 medium-6 small-12 panel left 
                     @Html.Raw(colors[index % colors.Length])"
                     data-equalizer-watch>
                    <div class="row">
                        <div class="column large-4 medium-4 small-4 left">
                            <img class="officerPicture" 
                                 src="~/@(Html.DisplayFor(modelItem => item.photo))" 
                                 alt="Officer photo" />
                        </div>
                        <div class="column large-8 medium-8 small-8 left">
                            <p>@Html.DisplayFor(modelItem => item.name)</p>
                            <p>@Html.DisplayFor(modelItem => item.description)</p>
                            <p>@Html.DisplayFor(modelItem => item.email)</p>
                        </div>
                    </div>
                </div>
                index++;
            }
        }
    </div>
</div>