NWS-cs/Models/Archive.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NWS_cs
{
    public partial class Archive
    {
        public Archive()
        {
            DateTime now = DateTime.Now;
            title = "New Archive Title: " + now.ToString();
        }

        public int id { get; set; }

        [DisplayName("Archive Title")]
        [Required(ErrorMessage = "Archive title is required")]
        public string title { get; set; }

        [DisplayName("Archive Link")]
        [Required(ErrorMessage = "Archive link is required")]
        public string link { get; set; }
    }
}

NWS-cs/Models/Archives.cs
namespace NWS_cs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Archives
    {
        public int id { get; set; }

        public string title { get; set; }

        public string link { get; set; }
    }
}

NWS-cs/Controllers/ArchiveController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class ArchiveController : Controller
    {
        private NwsContext db = new NwsContext();

        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        public ActionResult Index()
        {
            return View(db.Archives.ToList());
        }

        public ActionResult Content()
        {
            return View(db.Archives.ToList());
        }

        // GET: Archive/Create
        public ActionResult Create()
        {
            var model = new Archive();
            return View(model);
        }

        // POST: Archive/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "id,title,link")] Archive archive)
        {
            if (ModelState.IsValid)
            {
                db.Archives.Add(archive);
                db.SaveChanges();
                return RedirectToAction("Content");
            }

            return View(archive);
        }

        // GET: Archive/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Archive archive = db.Archives.Find(id);
            if (archive == null)
            {
                return HttpNotFound();
            }
            return View(archive);
        }

        // POST: Archive/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,title,link")] Archive archive)
        {
            if (ModelState.IsValid)
            {
                db.Entry(archive).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Content");
            }
            return View(archive);
        }

        // GET: Archive/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Archive archive = db.Archives.Find(id);
            if (archive == null)
            {
                return HttpNotFound();
            }
            return View(archive);
        }

        // POST: Archive/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Archive archive = db.Archives.Find(id);
            db.Archives.Remove(archive);
            db.SaveChanges();
            return RedirectToAction("Content");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NWS-cs/Controllers/EditController.cs
using System.Web.Mvc;

namespace NWS_cs.Controllers
{
    public class EditController : Controller
    {
        public ActionResult _EditButtonPartial()
        {
            return PartialView();
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

NWS-cs/Views/Archive/Content.cshtml
@model IEnumerable<NWS_cs.Archive>

@{
    ViewBag.Title = "Archive Content";
}

<div class="row bumpPastTopbar">
    @Html.Action("_EditButtonPartial", "Edit")

    <h4>Archives</h4>

    <p>
        <a href='@Url.Action("Create", "Archive")' class="button tiny">
            Create New
        </a>
    </p>

    @{
        foreach (var item in Model)
        {
            <div class="column large-12 medium-12 small-12 panel">
                <div class="row">
                    <div class="column small-2 left">
                        <a href='@Url.Action("Edit", "Archive", new { id=item.id })'>
                            Edit
                        </a>|
                        <a href='@Url.Action("Delete", "Archive", new { id=item.id })'>
                            Delete
                        </a>
                    </div>

                    <div class="column small-10 left">
                        <div class="row">
                            @Html.DisplayFor(modelItem => item.title)
                        </div>
                        <div class="row">
                            @Html.DisplayFor(modelItem => item.link)
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Archive/Create.cshtml
@model NWS_cs.Archive

@{
    ViewBag.Title = "Archive Create";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Create an Archive Item</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.title)
            <div class="column small-12">
                @Html.EditorFor(model => model.title)
                @Html.ValidationMessageFor(model => model.title)
            </div>

            @Html.LabelFor(model => model.link)
            <div class="column small-12">
                @Html.EditorFor(model => model.link)
                @Html.ValidationMessageFor(model => model.link)
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Archive")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Archive/Delete.cshtml
@model NWS_cs.Archive

@{
    ViewBag.Title = "Archive Delete";
}

@using (Html.BeginForm())
{
    <div class="row bumpPastTopbar">
        <h4>Delete an Archive Item</h4>

        <h5>Are you sure you want to delete this?</h5>

        <div class="column small-12 panel">
            <div class="row">
                <div class="column small-12 small-offset-2 left">
                    <div>
                        @Html.DisplayFor(model => model.title)
                    </div>
                    <div>
                         @Html.DisplayFor(model => model.link)
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Delete" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Archive")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Archive/Edit.cshtml
@model NWS_cs.Archive

@{
    ViewBag.Title = "Archive Edit";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="row bumpPastTopbar">
        <h4>Edit an Archive Item</h4>

        <div>
            @Html.LabelFor(model => model.title)
            <div class="column small-12">
                @Html.EditorFor(model => model.title)
                @Html.ValidationMessageFor(model => model.title)
            </div>

            @Html.LabelFor(model => model.link)
            <div class="column small-12">
                @Html.EditorFor(model => model.link)
                @Html.ValidationMessageFor(model => model.link)
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="button tiny" />
        </div>

        <a href='@Url.Action("Content", "Archive")' class="button tiny">
            Back to List
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWS-cs/Views/Archive/Index.cshtml
@model IEnumerable<NWS_cs.Archive>

@{
    ViewBag.Title = "Archives";
}

<div class="row bumpPastTopbar">
    <h4>Deer Park Neighborhood Association Archives</h4>

    <div class="row" data-equalizer>
        @{
            int index = 0;
            string[] colors = { "greenA", "greenB", "greenC" };
            foreach (var item in Model)
            {
                <div class="column small-12 panel left 
                     @Html.Raw(colors[index % colors.Length])">
                    <h5>
                        <a href="~/@Html.DisplayFor(modelItem => item.link)">@Html.DisplayFor(modelItem => item.title)</a>
                    </h5>
                </div>
                index++;
            }
        }
    </div>
</div>